/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame_Convertion;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author pian
 */
public class Suhu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Suhu.class.getName());

    /**
     * Creates new form Suhu
     */
    public Suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtreamur = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbtcelcius = new javax.swing.JRadioButton();
        rbfcelcius = new javax.swing.JRadioButton();
        rbfreamur = new javax.swing.JRadioButton();
        rbffahrenheit = new javax.swing.JRadioButton();
        rbtfahrenheit = new javax.swing.JRadioButton();
        rbfkelvin = new javax.swing.JRadioButton();
        rbtkelvin = new javax.swing.JRadioButton();
        btnhitung = new javax.swing.JButton();
        txtinput = new javax.swing.JTextField();
        txtoutput = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hasil");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("To");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("From");

        buttonGroup2.add(rbtreamur);
        rbtreamur.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbtreamur.setForeground(new java.awt.Color(51, 51, 51));
        rbtreamur.setText("Reamur");
        rbtreamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtreamurActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Input");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Conversion Suhu");

        buttonGroup2.add(rbtcelcius);
        rbtcelcius.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbtcelcius.setForeground(new java.awt.Color(51, 51, 51));
        rbtcelcius.setText("Celcius");
        rbtcelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcelciusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfcelcius);
        rbfcelcius.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbfcelcius.setForeground(new java.awt.Color(51, 51, 51));
        rbfcelcius.setText("Celcius");
        rbfcelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfcelciusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfreamur);
        rbfreamur.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbfreamur.setForeground(new java.awt.Color(51, 51, 51));
        rbfreamur.setText("Reamur");
        rbfreamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfreamurActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbffahrenheit);
        rbffahrenheit.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbffahrenheit.setForeground(new java.awt.Color(51, 51, 51));
        rbffahrenheit.setText("Fahrenheit");
        rbffahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbffahrenheitActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtfahrenheit);
        rbtfahrenheit.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbtfahrenheit.setForeground(new java.awt.Color(51, 51, 51));
        rbtfahrenheit.setText("Fahrenheit");
        rbtfahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtfahrenheitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfkelvin);
        rbfkelvin.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbfkelvin.setForeground(new java.awt.Color(51, 51, 51));
        rbfkelvin.setText("Kelvin");
        rbfkelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfkelvinActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtkelvin);
        rbtkelvin.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rbtkelvin.setForeground(new java.awt.Color(51, 51, 51));
        rbtkelvin.setText("Kelvin");
        rbtkelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtkelvinActionPerformed(evt);
            }
        });

        btnhitung.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        txtinput.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        txtinput.setToolTipText("");

        txtoutput.setBackground(new java.awt.Color(0, 0, 0));
        txtoutput.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtoutput.setForeground(new java.awt.Color(0, 0, 0));
        txtoutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbfcelcius)
                                .addComponent(rbfreamur))
                            .addComponent(rbffahrenheit)
                            .addComponent(rbfkelvin))
                        .addGap(246, 246, 246)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtfahrenheit)
                                    .addComponent(jLabel3)
                                    .addComponent(rbtreamur)
                                    .addComponent(rbtcelcius))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtkelvin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(230, Short.MAX_VALUE)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(187, 187, 187)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtcelcius)
                    .addComponent(rbfcelcius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtreamur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbfreamur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbffahrenheit)
                    .addComponent(rbtfahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfkelvin)
                    .addComponent(rbtkelvin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtreamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtreamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtreamurActionPerformed

    private void rbtcelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtcelciusActionPerformed

    private void rbfcelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfcelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfcelciusActionPerformed

    private void rbfreamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfreamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfreamurActionPerformed

    private void rbffahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbffahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbffahrenheitActionPerformed

    private void rbtfahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtfahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtfahrenheitActionPerformed

    private void rbfkelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfkelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfkelvinActionPerformed

    private void rbtkelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtkelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtkelvinActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        double input = Double.parseDouble(txtinput.getText());
        double hasil = 0;

        String from = "";
        String to = "";

        if (rbfcelcius.isSelected()) {
            from = "C";
        } else if (rbfreamur.isSelected()) {
            from = "R";
        } else if (rbffahrenheit.isSelected()) {
            from = "F";
        } else if (rbfkelvin.isSelected()) {
            from = "K";
        }

        if (rbtcelcius.isSelected()) {
            to = "C";
        } else if (rbtreamur.isSelected()) {
            to = "R";
        } else if (rbtfahrenheit.isSelected()) {
            to = "F";
        } else if (rbtkelvin.isSelected()) {
            to = "K";
        }

        switch (from) {
            case "C":
                switch (to) {
                    case "R":
                        hasil = (4.0 / 5) * input;
                        break;
                    case "F":
                        hasil = (9.0 / 5) * input + 32;
                        break;
                    case "K":
                        hasil = input + 273;
                        break;
                    default:
                        hasil = input;
                }
                break;

            case "R":
                switch (to) {
                    case "C":
                        hasil = (5.0 / 4) * input;
                        break;
                    case "F":
                        hasil = (9.0 / 4) * input + 32;
                        break;
                    case "K":
                        hasil = (5.0 / 4) * input + 273;
                        break;
                    default:
                        hasil = input;
                }
                break;

            case "F":
                switch (to) {
                    case "R":
                        hasil = (4.0 / 9) * (input - 32);
                        break;
                    case "C":
                        hasil = (5.0 / 9) * (input - 32);
                        break;
                    case "K":
                        hasil = (5.0 / 9) * (input - 32) + 273;
                        break;
                    default:
                        hasil = input;
                }
                break;

            case "K":
                switch (to) {
                    case "R":
                        hasil = (4.0 / 5) * (input - 273);
                        break;
                    case "F":
                        hasil = (9.0 / 5) * (input - 273) + 32;
                        break;
                    case "C":
                        hasil = input - 273;
                        break;
                    default:
                        hasil = input;
                }
                break;

            default:
                hasil = 0;
        }

        txtoutput.setText(String.format("%.2f", hasil));
    }//GEN-LAST:event_btnhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Suhu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbfcelcius;
    private javax.swing.JRadioButton rbffahrenheit;
    private javax.swing.JRadioButton rbfkelvin;
    private javax.swing.JRadioButton rbfreamur;
    private javax.swing.JRadioButton rbtcelcius;
    private javax.swing.JRadioButton rbtfahrenheit;
    private javax.swing.JRadioButton rbtkelvin;
    private javax.swing.JRadioButton rbtreamur;
    private javax.swing.JTextField txtinput;
    private javax.swing.JLabel txtoutput;
    // End of variables declaration//GEN-END:variables
}
